"""
Quality Checker Module.

This module provides the `QualityChecker` class and the `CaptionValidationError`
exception. It is responsible for enforcing strict structural and content rules
on generated captions to ensure they meet the modern requirements for T5/DiT 
LoRA training datasets.
"""


class CaptionValidationError(Exception):
    """
    Custom exception raised when a caption fails quality validation.
    
    The exception message contains specific, actionable feedback intended to be 
    passed back to the Vision-Language Model to prompt an automated self-correction.
    """
    pass


class QualityChecker:
    """
    Enforces strict structural and content rules for T5/DiT LoRA captions.
    
    This class verifies that generated captions contain the required trigger word,
    fall strictly within configured word count boundaries, avoid conversational AI 
    filler, and use natural language instead of comma-separated Booru-style tags.
    """
    
    def __init__(self, trigger_word: str, min_words: int, max_words: int):
        """
        Initializes the QualityChecker with specific validation boundaries.

        Args:
            trigger_word (str): The specific token/word that must be present in the caption.
            min_words (int): The minimum acceptable word count for a generated caption.
            max_words (int): The maximum acceptable word count for a generated caption.
        """
        # Normalize the trigger word for case-insensitive matching
        self.trigger_word = trigger_word.lower().strip()
        self.min_words = min_words
        self.max_words = max_words
        
        # Common AI conversational filler we don't want polluting training datasets
        self.ai_slop = [
            "here is", "this image shows", "the picture displays", 
            "as an ai", "i can see", "in this image", "the provided image"
        ]

    def validate(self, caption: str) -> bool:
        """
        Evaluates a generated caption against all configured quality rules.

        Args:
            caption (str): The raw text caption generated by the AI model.

        Returns:
            bool: True if the caption passes all validation checks.

        Raises:
            CaptionValidationError: If the caption fails any check. The exception 
                                    will contain specific instructions for correction.
        """
        caption_lower = caption.lower()

        # 1. Trigger Word Check
        # Ensures the LoRA trigger token is natively bound to the image description
        if self.trigger_word not in caption_lower:
            raise CaptionValidationError(
                f"Your caption MUST include the trigger word '{self.trigger_word}'. "
                f"Please rewrite it to include '{self.trigger_word}' naturally."
            )

        # 2. AI Slop Check
        # Prevents the model from acting like a chatbot instead of a clinical describer
        for slop in self.ai_slop:
            if slop in caption_lower:
                raise CaptionValidationError(
                    f"Do not use conversational filler like '{slop}'. Start the description directly."
                )

        # 3. Density / Word Count Check
        # Split the caption by whitespace to approximate the total word count
        word_count = len(caption.split())
        
        # Enforce minimum density for heavy LLM-based text encoders (e.g., T5)
        if word_count < self.min_words:
            raise CaptionValidationError(
                f"Your caption is too short ({word_count} words). "
                f"Expand on the clothing, lighting, and background details to reach at least {self.min_words} words."
            )
            
        # Enforce maximum density to prevent runaway hallucinations beyond the frame boundaries
        if word_count > self.max_words:
            raise CaptionValidationError(
                f"Your caption is too long ({word_count} words). "
                f"Edit it down to be more concise. The maximum allowed length is {self.max_words} words."
            )

        # 4. Format Check (No Booru Tags)
        # Rejects the caption if it contains an excessive ratio of commas to words,
        # which strongly indicates outdated Danbooru-style tag lists instead of prose.
        if caption.count(",") > (word_count / 5):
            raise CaptionValidationError(
                "You are using too many commas, which suggests Booru-style tagging. "
                "Rewrite the caption using flowing, continuous natural language sentences."
            )

        return True
    